# Site settings
title: Workout Assistant
email: jeremyminton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a webapp to guide you through workouts by providing
  timed exercise routines.
baseurl: "" #/mnt/raid/Projects_Assorted/workoutWebApp/build/" # the subpath of your site, e.g. /blog/
destination: "./build/workouts"
source: "./source/"
url: "http://jeremyminton.co.nz" # the base hostname & protocol for your site


owner:
    name: Jeremy Minton
    email: jeremyminton at gmail.com
    website: jeremyminton.co.nz
    twitter: #
    github: JJMinton
    disqus_shortname: #

github_username:  JJMinton

# Build settings
markdown: kramdown
